name: Windows build for Zed

on:
  push:
    tags:
      - "daily-release-[0-9]+"
  workflow_run:
    workflows: ["Daily release"]
    types:
      - completed

permissions:
  pull-requests: read
  statuses: write
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Configure long path
        run: git config --global core.longpaths true

      - name: Clone zed
        run: git clone https://github.com/zed-industries/zed.git

      - name: Build Zed
        run: |
          cd zed
          cargo build --release
      
      - name: Zip file
        run: |
          cd zed/target/release/
          zip zed zed.exe

      - name: Upload Setup Wizard
        uses: actions/upload-artifact@v4
        with:
          name: zed
          # path: ./zed/target/release/zed.exe
          path: ./zed/target/release/zed.zip
          overwrite: true

  Upload:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download Release Folder
        uses: actions/download-artifact@v4
        with:
          name: zed
          path: Output

      - name: Setup Git Environment
        run: |
          git config --global user.email 41898111+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]

      - name: Generate Release Tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d")"
          echo "::set-output name=release_date::$(date +"%Y.%m.%d")"     
          
      - name: Upload to Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.release_date }} Zed Windows
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ./Output/zed.zip